#pragma once
#include <Toshi/Toshi.h>

#ifndef PGUIRENDERER_STATIC_LINKING

#  ifdef PGUIRENDERER
#	define PGUIRENDERER_EXPORTS DLL_CLASS_EXPORT
#  else
#	define PGUIRENDERER_EXPORTS DLL_CLASS_IMPORT
#  endif

#else // !PGUIRENDERER_STATIC_LINKING

#  define PGUIRENDERER_EXPORTS

#endif // PGUIRENDERER_STATIC_LINKING
