#pragma once
#include <Toshi/Toshi.h>

#ifndef TRENDERINTERFACED3D_STATIC_LINKING

#  ifdef TRENDERINTERFACED3D
#	define TRENDERINTERFACED3D_EXPORTS DLL_CLASS_EXPORT
#  else
#	define TRENDERINTERFACED3D_EXPORTS DLL_CLASS_IMPORT
#  endif

#else // !TRENDERINTERFACED3D_STATIC_LINKING

#  define TRENDERINTERFACED3D_EXPORTS

#endif // TRENDERINTERFACED3D_STATIC_LINKING
