#include "TMemoryDebug.h"

#ifdef TKERNELINTERFACE_ENABLE_MEMORY_PROFILER

TKERNELINTERFACE_EXPORTS const TCHAR* TMemory__FUNC__ = TNULL;
TKERNELINTERFACE_EXPORTS const TCHAR* TMemory__FILE__ = TNULL;
TKERNELINTERFACE_EXPORTS TINT         TMemory__LINE__ = -1;

#endif // TKERNELINTERFACE_ENABLE_MEMORY_PROFILER
