#pragma once
#include <Toshi/Toshi.h>

#ifndef TAPPLICATION_STATIC_LINKING

#  ifdef TAPPLICATION
#	define TAPPLICATION_EXPORTS DLL_CLASS_EXPORT
#  else
#	define TAPPLICATION_EXPORTS DLL_CLASS_IMPORT
#  endif

#else // !TAPPLICATION_STATIC_LINKING

#  define TAPPLICATION_EXPORTS

#endif // TAPPLICATION_STATIC_LINKING
