#pragma once
#include <Toshi/Toshi.h>

#ifndef TRENDERINTERFACE_STATIC_LINKING

#ifdef TRENDERINTERFACE
#define TRENDERINTERFACE_EXPORTS DLL_CLASS_EXPORT
#else
#define TRENDERINTERFACE_EXPORTS DLL_CLASS_IMPORT
#endif

#else  // !TRENDERINTERFACE_STATIC_LINKING

#define TRENDERINTERFACE_EXPORTS

#endif // TRENDERINTERFACE_STATIC_LINKING