#pragma once
#include <Toshi/Toshi.h>

#ifndef TGUIINTERFACE_STATIC_LINKING

#ifdef TGUIINTERFACE
#define TGUIINTERFACE_EXPORTS DLL_CLASS_EXPORT
#else
#define TGUIINTERFACE_EXPORTS DLL_CLASS_IMPORT
#endif

#else  // !TGUIINTERFACE_STATIC_LINKING

#define TGUIINTERFACE_EXPORTS

#endif // TGUIINTERFACE_STATIC_LINKING