#pragma once
#include <Toshi/Toshi.h>

#ifndef TTERRAININTERFACE_STATIC_LINKING

#  ifdef TTERRAININTERFACE
#	define TTERRAININTERFACE_EXPORTS DLL_CLASS_EXPORT
#  else
#	define TTERRAININTERFACE_EXPORTS DLL_CLASS_IMPORT
#  endif

#else // !TTERRAININTERFACE_STATIC_LINKING

#  define TTERRAININTERFACE_EXPORTS

#endif // TTERRAININTERFACE_STATIC_LINKING
