#pragma once
#include <Toshi/Toshi.h>

#ifndef TSYSSHADERD3D_STATIC_LINKING

#ifdef TSYSSHADERD3D
#define TSYSSHADERD3D_EXPORTS DLL_CLASS_EXPORT
#else
#define TSYSSHADERD3D_EXPORTS DLL_CLASS_IMPORT
#endif

#else  // !TSYSSHADERD3D_STATIC_LINKING

#define TSYSSHADERD3D_EXPORTS

#endif // TSYSSHADERD3D_STATIC_LINKING