#pragma once
#include <Toshi/Toshi.h>

#ifndef PPROPERTYPARSER_STATIC_LINKING

#ifdef PPROPERTYPARSER
#define PPROPERTYPARSER_EXPORTS DLL_CLASS_EXPORT
#else
#define PPROPERTYPARSER_EXPORTS DLL_CLASS_IMPORT
#endif

#else  // !PPROPERTYPARSER_STATIC_LINKING

#define PPROPERTYPARSER_EXPORTS

#endif // PPROPERTYPARSER_STATIC_LINKING