#pragma once
#include "TKernel/Defines.h"

#ifdef TKERNELINTERFACE_ENABLE_MEMORY_PROFILER

extern TKERNELINTERFACE_EXPORTS const TCHAR* TMemory__FUNC__;
extern TKERNELINTERFACE_EXPORTS const TCHAR* TMemory__FILE__;
extern TKERNELINTERFACE_EXPORTS TINT         TMemory__LINE__;

#endif // TKERNELINTERFACE_ENABLE_MEMORY_PROFILER
