#pragma once
#include <Toshi/Toshi.h>

#ifndef TSPRITESHADERD3D_STATIC_LINKING

#ifdef TSPRITESHADERD3D
#define TSPRITESHADERD3D_EXPORTS DLL_CLASS_EXPORT
#else
#define TSPRITESHADERD3D_EXPORTS DLL_CLASS_IMPORT
#endif

#else  // !TSPRITESHADERD3D_STATIC_LINKING

#define TSPRITESHADERD3D_EXPORTS

#endif // TSPRITESHADERD3D_STATIC_LINKING